name: build-and-test

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Get Meson
      run: pip3 install meson ninja

    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      shell: bash
      run: meson setup builddir

    - name: Build
      working-directory: ${{github.workspace}}/builddir
      shell: bash
      run: meson compile

    - name: Test
      working-directory: ${{github.workspace}}/builddir
      shell: bash
      run: meson test
